version: '3'
services:
  expresscart:
    image: "node:18-alpine"
    build: .
    container_name: "expresscart"
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_PATH: ${NODE_PATH}
      DD_ENV: ${DD_ENV}                             # DataKit environment
      DD_AGENT_HOST: ${DD_AGENT_HOST}               # Must use localhost IP address. Containers unable to access localhost
      DD_TRACE_AGENT_PORT: ${DD_TRACE_AGENT_PORT}
      DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED: ${DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED}  # DataKit trace port (default: 9529)
      DD_SERVICE: ${DD_SERVICE_EXPRESSCART}
    ports:
      - "1111:1111"
    links:
      - mongodb
    depends_on:
      - mongodb
  nginx:
    build: ./nginx
    container_name: "expresscart-nginx"  
    environment:
      DD_AGENT_HOST: ${DD_AGENT_HOST}               # Must use localhost IP address. Containers unable to access localhost
      DD_TRACE_AGENT_PORT: ${DD_TRACE_AGENT_PORT}   # DataKit trace port (default: 9529)
      DD_SERVICE: ${DD_SERVICE_NGINX}              # Service name
      DD_LOGS_INJECTION: ${DD_LOGS_INJECTION}
      DD_ENV: ${DD_ENV}
      DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED: ${DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - '8080:8080'
    depends_on:
      - expresscart
  mongodb:
    image: mongo:latest
    container_name: "expresscart-mongodb"
    environment:
      DD_AGENT_HOST: ${DD_AGENT_HOST}               # Must use localhost IP address. Containers unable to access localhost
      DD_TRACE_AGENT_PORT: ${DD_TRACE_AGENT_PORT}   # DataKit trace port (default: 9529)
      DD_SERVICE: ${DD_SERVICE_EXPRESSCART}
      DD_ENV: ${DD_ENV}                             # Service name
    volumes:
      - expresscart-mongo-data:/data/db
    ports:
      - 27017:27017
    command: mongod 
volumes:
  expresscart-mongo-data:
